### ISSUE TITLE
Bug: collections handler fails because action.location is NULL

### ISSUE THREAD

**Issue by BertR** [edina/nbexchange#84]
I've got a request:

Could you write a test for nbexchange that 

```
Calls the collections handler 
- for a valid instructor
- for a valid course
- With a valid submission for that course
- With a feedback_fetched action for that assignment with an empty "location" field
```

This should break the collections handler (as it did for one of our users in UniDesk call I210419-1741).
Once the test is written (and red), we can think about ways to fix this.

**Comment by perllaghu** [comment]
Can I confirm you're talking collection of a student submission rather than collection of feedback by a student (where the location is null)

The collection of a student submission should have no interest in whether feedback exists or not.

We should also consider verifying that location is always defined, for every action... and how we fail when that location has not been defined

**Comment by BertR** [comment]
> Can I confirm you're talking collection of a student submission rather than collection of feedback by a student (where the location is null)
> 
> The collection of a student submission should have no interest in whether feedback exists or not.
> 
> We should also consider verifying that location is always defined, for every action... and how we fail when that location has not been defined

`GET /services/nbexchange/collections` is the handler this is about.

**Comment by perllaghu** [comment]
I'll have a look - that handler should not care about feedback at all.

**Comment by perllaghu** [comment]
I didn't think it would make a difference

Branch `84_blank_path_breaks_collections` has three additional tests
